### ISSUE TITLE
Add license file

### ISSUE THREAD

**Issue by navopw** [Drinkler/Vier-gewinnt#31]
Mit einer LICENSE Datei könnt ihr die Lizenz für euer Projekt bestimmen. GitHub erkennt diese automatisch und setzt die Lizenz für euer Projekt.

Ist vorteilhaft, da sonst nicht geregelt ist in wie fern man das Projekt benutzen darf.

(PS: Cooles Projekt 👍)

**Comment by lucastanger** [comment]
Ist doch schon drin?

**Comment by navopw** [comment]
Übersehen, sorry.
